/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SEO Specialist API
 * API documentation for SEO Specialist application
 * OpenAPI spec version: 0.0.1
 */
import * as zod from 'zod';

/**
 * @summary Get all users
 */
export const usersControllerFindAllResponseItem = zod.object({
  "id": zod.number().describe('User ID'),
  "email": zod.string().describe('User email'),
  "name": zod.string().nullish().describe('User name'),
  "createdAt": zod.string().datetime({}).describe('Creation date'),
  "updatedAt": zod.string().datetime({}).describe('Last update date')
})
export const usersControllerFindAllResponse = zod.array(usersControllerFindAllResponseItem)
