/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SEO Specialist API
 * API documentation for SEO Specialist application
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { UsersDTO } from './schemas';

import { createInstance } from '../../api.instance';
import type { ErrorType } from '../../api.instance';
type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export const appControllerGetData = (signal?: AbortSignal) => {
  return createInstance<void>({ url: `/api/pro`, method: 'GET', signal });
};

export const getAppControllerGetDataQueryKey = () => {
  return [`/api/pro`] as const;
};

export const getAppControllerGetDataQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetData>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetData>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerGetDataQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof appControllerGetData>>
  > = ({ signal }) => appControllerGetData(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetData>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AppControllerGetDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetData>>
>;
export type AppControllerGetDataQueryError = ErrorType<unknown>;

export function useAppControllerGetData<
  TData = Awaited<ReturnType<typeof appControllerGetData>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetData>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAppControllerGetDataQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const appControllerWhoami = (signal?: AbortSignal) => {
  return createInstance<void>({ url: `/api/whoami`, method: 'GET', signal });
};

export const getAppControllerWhoamiQueryKey = () => {
  return [`/api/whoami`] as const;
};

export const getAppControllerWhoamiQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerWhoami>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof appControllerWhoami>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerWhoamiQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof appControllerWhoami>>
  > = ({ signal }) => appControllerWhoami(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerWhoami>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AppControllerWhoamiQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerWhoami>>
>;
export type AppControllerWhoamiQueryError = ErrorType<unknown>;

export function useAppControllerWhoami<
  TData = Awaited<ReturnType<typeof appControllerWhoami>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof appControllerWhoami>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getAppControllerWhoamiQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get all users
 */
export const usersControllerFindAll = (signal?: AbortSignal) => {
  return createInstance<UsersDTO[]>({
    url: `/api/users`,
    method: 'GET',
    signal,
  });
};

export const getUsersControllerFindAllQueryKey = () => {
  return [`/api/users`] as const;
};

export const getUsersControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerFindAll>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerFindAll>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUsersControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerFindAll>>
  > = ({ signal }) => usersControllerFindAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type UsersControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerFindAll>>
>;
export type UsersControllerFindAllQueryError = ErrorType<unknown>;

/**
 * @summary Get all users
 */

export function useUsersControllerFindAll<
  TData = Awaited<ReturnType<typeof usersControllerFindAll>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerFindAll>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getUsersControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
