/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SEO Specialist API
 * API documentation for SEO Specialist application
 * OpenAPI spec version: 0.0.1
 */

export interface UsersDTO {
  /** User ID */
  id: number;
  /** User email */
  email: string;
  /**
   * User name
   * @nullable
   */
  name?: string | null;
  /** Creation date */
  createdAt: string;
  /** Last update date */
  updatedAt: string;
}
